// Import Angular core utilities: Component, inject for DI, OnInit lifecycle, signal for reactive state, computed for derived state
import { Component, inject, OnInit, signal, computed } from '@angular/core';
// HttpClient for fetching calendar tasks directly from the dashboard endpoint
import { HttpClient } from '@angular/common/http';
// DatePipe formats dates in the template
import { DatePipe } from '@angular/common';
// FormsModule enables [(ngModel)] for the day notes textarea
import { FormsModule } from '@angular/forms';
// Environment config provides the base API URL for the calendar endpoint
import { environment } from '../../../environments/environment';
// Task model interface for typing
import { Task } from '../../core/models/task.model';
// ModalComponent wraps the task form in a dialog for adding tasks from the calendar
import { ModalComponent } from '../../shared/components/modal/modal.component';
// TaskFormComponent renders the task creation form inside the modal
import { TaskFormComponent } from '../tasks/task-form/task-form.component';

// CalendarDay represents a single cell in the monthly calendar grid.
// Each cell knows its date, whether it belongs to the current month,
// whether it is today, and what tasks are scheduled on that date.
interface CalendarDay {
  date: Date; // The date this cell represents
  isCurrentMonth: boolean; // False for padding days from previous/next months
  isToday: boolean; // True if this date matches today's date
  tasks: Task[]; // Tasks that have their dueDate on this date
}

// CalendarComponent displays a monthly calendar grid with tasks plotted on their due dates.
// Users can navigate between months, click on a day to see its tasks in a side panel,
// and add new tasks pre-filled with the selected date. Each day cell shows up to 3 task
// chips with a "+N more" indicator for overflow.
@Component({
  selector: 'app-calendar', // Loaded by the router at /calendar
  standalone: true, // Angular 19 standalone component
  imports: [DatePipe, FormsModule, ModalComponent, TaskFormComponent],
  template: `
    <!-- Page container with fade-in animation -->
    <div class="page animate-in">
      <!-- Calendar header: prev/next month buttons, month/year title, today button -->
      <div class="cal-header">
        <!-- Previous month button -->
        <button class="btn-ghost nav-btn" (click)="prevMonth()">
          <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><polyline points="15 18 9 12 15 6"/></svg>
        </button>
        <!-- Current month and year display -->
        <h2>{{ viewDate() | date:'MMMM y' }}</h2>
        <!-- Next month button -->
        <button class="btn-ghost nav-btn" (click)="nextMonth()">
          <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><polyline points="9 18 15 12 9 6"/></svg>
        </button>
        <!-- "Today" button: jumps back to the current month -->
        <button class="btn-ghost today-btn" (click)="goToday()">Today</button>
      </div>

      <!-- 7-column grid: day labels header + 42 day cells (6 weeks to cover any month layout) -->
      <div class="cal-grid card">
        <!-- Day-of-week labels: Sun through Sat -->
        @for (day of dayLabels; track day; let i = $index) {
          <div class="cal-label" [class.weekend-label]="i === 0 || i === 6">{{ day }}</div>
        }

        <!-- Day cells: generated by the computed grid() signal -->
        @for (cell of grid(); track cell.date.toISOString()) {
          <!-- Each cell: click opens the day detail panel -->
          <div class="cal-cell" [class.other-month]="!cell.isCurrentMonth" [class.today]="cell.isToday"
               [class.weekend]="cell.date.getDay() === 0 || cell.date.getDay() === 6"
               (click)="openDay(cell)">
            <!-- Day number: highlighted with accent color if it is today -->
            <span class="cal-date">{{ cell.date | date:'d' }}</span>
            <!-- Task chips: show up to 3 tasks per cell -->
            <div class="cal-tasks">
              @for (task of cell.tasks.slice(0, 3); track task.id) {
                <div class="cal-task-chip" [class.done]="task.status === 'DONE'">
                  <!-- Show start time prefix if available -->
                  @if (task.startTime) {
                    <span class="chip-time">{{ task.startTime }}</span>
                  }
                  {{ task.title }}
                </div>
              }
              <!-- Overflow indicator when more than 3 tasks are on one day -->
              @if (cell.tasks.length > 3) {
                <div class="cal-more">+{{ cell.tasks.length - 3 }} more</div>
              }
            </div>
          </div>
        }
      </div>
    </div>

    <!-- Day Detail Side Panel: slides in from the right when a day cell is clicked -->
    @if (selectedDay()) {
      <!-- Overlay: click to close the panel -->
      <div class="day-overlay" (click)="closeDay()"></div>
      <div class="day-panel animate-in">
        <!-- Panel header: day name, full date, close button -->
        <div class="day-panel-header">
          <div>
            <h3>{{ selectedDay()!.date | date:'EEEE' }}</h3>
            <p>{{ selectedDay()!.date | date:'MMMM d, y' }}</p>
          </div>
          <button class="icon-btn" (click)="closeDay()">
            <svg width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
          </button>
        </div>

        <!-- Tasks for the selected day -->
        <div class="day-tasks">
          <div class="day-section-hd">
            <span>Tasks</span>
            <!-- Button to add a new task pre-filled with the selected date -->
            <button class="btn-primary sm" (click)="showAddTask = true">+ Add</button>
          </div>

          <!-- Empty state for days with no tasks -->
          @if (selectedDay()!.tasks.length === 0) {
            <div class="day-empty">No tasks scheduled for this day</div>
          } @else {
            <!-- Task list within the day panel -->
            @for (task of selectedDay()!.tasks; track task.id) {
              <div class="day-task-row" [class.done]="task.status === 'DONE'">
                <div class="day-task-left">
                  <!-- Priority dot: color-coded (red=HIGH, amber=MEDIUM, green=LOW) -->
                  <span class="dot dot-{{ task.priority.toLowerCase() }}"></span>
                  <div class="day-task-info">
                    <span class="day-task-title">{{ task.title }}</span>
                    <!-- Time range if available -->
                    @if (task.startTime || task.endTime) {
                      <span class="day-task-time">
                        <svg width="12" height="12" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                        {{ task.startTime ?? '?' }} - {{ task.endTime ?? '?' }}
                      </span>
                    }
                  </div>
                </div>
                <!-- Status badge -->
                <span class="badge badge-{{ task.status.toLowerCase().replace('_', '-') }}">{{ task.status.replace('_', ' ') }}</span>
              </div>
            }
          }
        </div>

        <!-- Quick notes section: text area for free-form daily notes (client-side only) -->
        <div class="day-notes">
          <div class="day-section-hd"><span>Quick Note</span></div>
          <textarea class="input note-input" [(ngModel)]="dayNote" placeholder="What did you do today? Add notes here..." rows="3"></textarea>
        </div>
      </div>
    }

    <!-- Add Task modal: pre-fills the task form with the selected day's date -->
    <app-modal [isOpen]="showAddTask" title="Add Task" (close)="showAddTask = false">
      <app-task-form [task]="prefillTask" (saved)="onTaskAdded()" (cancelled)="showAddTask = false" />
    </app-modal>
  `,
  styles: [`
    /* Calendar header: horizontal flex with centered month/year title */
    .cal-header { display: flex; align-items: center; gap: 0.75rem; }
    .cal-header h2 { font-size: 1.25rem; font-weight: 700; color: var(--text-primary); margin: 0; min-width: 180px; text-align: center; }
    .nav-btn { padding: 6px 10px; }
    /* "Today" button pushed to the right */
    .today-btn { margin-left: auto; font-size: 0.82rem; }
    /* 7-column grid: 1px gap creates grid lines via the card's background color */
    .cal-grid {
      display: grid; grid-template-columns: repeat(7, 1fr); gap: 1px;
      background: var(--border); overflow: hidden; border-radius: var(--radius);
    }
    /* Day-of-week header labels: centered uppercase text */
    .cal-label {
      background: var(--bg-card); padding: 10px; text-align: center;
      font-size: 0.72rem; font-weight: 600; color: var(--text-muted);
      text-transform: uppercase; letter-spacing: 0.05em;
    }
    /* Day cells: minimum height to show a few task chips */
    .cal-cell {
      background: var(--bg-card); min-height: 110px; padding: 8px;
      display: flex; flex-direction: column; gap: 3px; cursor: pointer;
      transition: background 0.1s;
    }
    .cal-cell:hover { background: var(--bg-hover); }
    /* Cells from adjacent months: dimmed background */
    .cal-cell.other-month { background: var(--bg-secondary); }
    /* Today's cell: day number shown inside a green circle */
    .cal-cell.today .cal-date { background: var(--accent); color: white; border-radius: 50%; width: 24px; height: 24px; display: flex; align-items: center; justify-content: center; font-weight: 600; }
    /* Day number: small, centered */
    .cal-date { font-size: 0.8rem; font-weight: 500; color: var(--text-secondary); width: 24px; height: 24px; display: flex; align-items: center; justify-content: center; }
    .cal-cell.other-month .cal-date { color: var(--text-muted); }
    /* Task chips container within a day cell */
    .cal-tasks { display: flex; flex-direction: column; gap: 2px; flex: 1; }
    /* Individual task chip: small pill with accent styling */
    .cal-task-chip {
      font-size: 0.68rem; padding: 2px 6px; border-radius: 4px; font-weight: 500;
      white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
      background: var(--accent-subtle); color: var(--accent);
    }
    /* Done task chips: strikethrough and faded */
    .cal-task-chip.done { text-decoration: line-through; opacity: 0.5; }
    .chip-time { font-weight: 600; margin-right: 3px; }
    /* Overflow indicator for days with more than 3 tasks */
    .cal-more { font-size: 0.65rem; color: var(--text-muted); padding: 1px 4px; }

    /* Weekend cells */
    .cal-cell.weekend { background: #f3f4f6; }
    .cal-cell.weekend.other-month { background: #eaebee; }
    [data-theme="dark"] .cal-cell.weekend { background: #0a0a0c; }
    [data-theme="dark"] .cal-cell.weekend.other-month { background: #070709; }
    .cal-cell.weekend .cal-date { color: var(--accent); font-weight: 600; }
    .weekend-label { color: var(--accent) !important; font-weight: 700 !important; }

    /* Day Detail Side Panel */
    /* Overlay: semi-transparent backdrop behind the panel */
    .day-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.4); z-index: 900; }
    /* Panel: fixed on the right side of the viewport */
    .day-panel {
      position: fixed; top: 0; right: 0; bottom: 0; width: 400px;
      background: var(--bg-card); border-left: 1px solid var(--border);
      z-index: 901; display: flex; flex-direction: column;
      box-shadow: -8px 0 30px rgba(0,0,0,0.15); overflow-y: auto;
    }
    /* Panel header */
    .day-panel-header {
      display: flex; justify-content: space-between; align-items: flex-start;
      padding: 1.5rem; border-bottom: 1px solid var(--border);
    }
    .day-panel-header h3 { font-size: 1.125rem; font-weight: 700; margin: 0 0 2px; color: var(--text-primary); }
    .day-panel-header p { font-size: 0.82rem; color: var(--text-secondary); margin: 0; }

    /* Tasks section within the day panel */
    .day-tasks { padding: 1rem 1.5rem; }
    .day-section-hd { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem; }
    .day-section-hd span { font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; color: var(--text-muted); }
    .sm { font-size: 0.78rem; padding: 6px 12px; }
    .day-empty { text-align: center; padding: 1.5rem; color: var(--text-muted); font-size: 0.85rem; }

    /* Task rows within the day panel */
    .day-task-row {
      display: flex; align-items: center; justify-content: space-between; gap: 10px;
      padding: 10px 8px; border-radius: 8px; border-bottom: 1px solid var(--border);
    }
    .day-task-row:last-child { border-bottom: none; }
    .day-task-row.done .day-task-title { text-decoration: line-through; color: var(--text-muted); }
    .day-task-left { display: flex; align-items: center; gap: 10px; min-width: 0; flex: 1; }
    /* Priority dot: small colored circle */
    .dot { width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; }
    .dot-high { background: var(--red); } .dot-medium { background: var(--orange); } .dot-low { background: var(--green); }
    .day-task-info { display: flex; flex-direction: column; min-width: 0; }
    .day-task-title { font-size: 0.875rem; color: var(--text-primary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
    .day-task-time { display: flex; align-items: center; gap: 4px; font-size: 0.72rem; color: var(--accent); font-weight: 500; margin-top: 2px; }

    /* Quick notes section */
    .day-notes { padding: 1rem 1.5rem; border-top: 1px solid var(--border); }
    .note-input { font-size: 0.85rem; min-height: 60px; }

    /* Icon button for the close button */
    .icon-btn { background: transparent; border: none; padding: 6px; border-radius: 6px; cursor: pointer; color: var(--text-muted); display: flex; }
    .icon-btn:hover { background: var(--bg-hover); color: var(--text-primary); }
  `],
})
export class CalendarComponent implements OnInit {
  // HttpClient for fetching tasks for the current month from the calendar API endpoint
  private http = inject(HttpClient);

  // Day-of-week labels displayed in the grid header row
  dayLabels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  // Signal holding the currently viewed month (used for navigation and grid computation)
  viewDate = signal(new Date());
  // Signal holding all tasks for the current month (fetched from the backend)
  tasks = signal<Task[]>([]);
  // Signal holding the currently selected day (null when no day panel is open)
  selectedDay = signal<CalendarDay | null>(null);
  // Controls visibility of the "Add Task" modal
  showAddTask = false;
  // Two-way bound value for the quick notes textarea in the day panel
  dayNote = '';
  // Pre-filled task data passed to the TaskFormComponent when adding from the calendar
  prefillTask: any = null;

  // Computed signal that generates the 42-cell calendar grid (6 rows x 7 columns)
  // whenever viewDate or tasks change. This ensures the grid reactively updates.
  grid = computed<CalendarDay[]>(() => {
    const d = this.viewDate();
    const year = d.getFullYear();
    const month = d.getMonth();
    // Day of week for the 1st of the month (0=Sun, 6=Sat) — determines padding cells
    const firstDay = new Date(year, month, 1).getDay();
    // Total days in the current month
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    const today = new Date();
    const cells: CalendarDay[] = [];

    // Fill padding cells from the previous month (so the grid starts on Sunday)
    const prevMonthDays = new Date(year, month, 0).getDate();
    for (let i = firstDay - 1; i >= 0; i--) {
      cells.push({ date: new Date(year, month - 1, prevMonthDays - i), isCurrentMonth: false, isToday: false, tasks: [] });
    }
    // Fill cells for the current month's days
    for (let i = 1; i <= daysInMonth; i++) {
      const date = new Date(year, month, i);
      const isToday = date.toDateString() === today.toDateString();
      // Filter tasks that have their dueDate on this specific day
      const dayTasks = this.tasks().filter((t) => {
        if (!t.dueDate) return false;
        const d2 = new Date(t.dueDate);
        return d2.getFullYear() === year && d2.getMonth() === month && d2.getDate() === i;
      });
      cells.push({ date, isCurrentMonth: true, isToday, tasks: dayTasks });
    }
    // Fill remaining cells with next month's days to complete the 6x7 grid (42 cells)
    const remaining = 42 - cells.length;
    for (let i = 1; i <= remaining; i++) {
      cells.push({ date: new Date(year, month + 1, i), isCurrentMonth: false, isToday: false, tasks: [] });
    }
    return cells;
  });

  // On init, fetch tasks for the initially displayed month
  ngOnInit() { this.loadTasks(); }

  // Navigate to the previous month and reload tasks
  prevMonth() { this.viewDate.update((d) => new Date(d.getFullYear(), d.getMonth() - 1, 1)); this.loadTasks(); }
  // Navigate to the next month and reload tasks
  nextMonth() { this.viewDate.update((d) => new Date(d.getFullYear(), d.getMonth() + 1, 1)); this.loadTasks(); }
  // Jump to the current month and reload tasks
  goToday()   { this.viewDate.set(new Date()); this.loadTasks(); }

  // Open the day detail side panel for the clicked cell
  openDay(cell: CalendarDay) {
    this.selectedDay.set(cell); // Set the selected day signal to show the panel
    this.dayNote = ''; // Reset the notes field
    // Pre-fill the task form with the selected date so new tasks default to this day
    const dateStr = cell.date.toISOString().split('T')[0];
    this.prefillTask = { dueDate: dateStr, startTime: null, endTime: null } as any;
  }

  // Close the day detail panel
  closeDay() { this.selectedDay.set(null); }

  // Called when a new task is added from the calendar — refresh the grid and panel
  onTaskAdded() {
    this.showAddTask = false; // Close the modal
    this.loadTasks(); // Reload all tasks for the month
    // Refresh the selected day's task list after a short delay to allow the grid to recompute
    if (this.selectedDay()) {
      setTimeout(() => {
        const day = this.selectedDay()!;
        // Find the updated cell from the recomputed grid and update the selected day
        const refreshed = this.grid().find((c) => c.date.toDateString() === day.date.toDateString());
        if (refreshed) this.selectedDay.set(refreshed);
      }, 500);
    }
  }

  // Fetch all tasks for the currently viewed month from the backend calendar endpoint
  private loadTasks() {
    const d = this.viewDate();
    this.http.get<Task[]>(`${environment.apiUrl}/dashboard/calendar`, {
      params: { year: String(d.getFullYear()), month: String(d.getMonth() + 1) }, // Backend expects 1-indexed month
    }).subscribe((t) => this.tasks.set(t)); // Update the tasks signal which triggers grid recomputation
  }
}
